### PR TITLE
Bump version to 2017.5

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by isuruf** [comment]
Is this a pure python package that is identical for all python versions and OSes? https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#architecture-independent-packages

**Comment by inducer** [comment]
@isuruf Thanks for bringing that to my attention! I did not know about it. I've just pushed another two commits that change the feedstock to make use of that.

**Comment by isuruf** [comment]
Np. For future reference, we've got a bot that can do it for you. https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-add-noarch-python

**Comment by inducer** [comment]
Nice! TIL even more. :)

**Pull request merged**
