### PR TITLE
[ci skip] ***NO_CI*** adding bot automerge

### LINKED ISSUE #23: @conda-forge-admin, add bot automerge
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added bot automerge as instructed in #23.

Merge this PR to enable bot automerging.

Fixes #23

### CODE REVIEW

**Comment by isuruf** [comment]
@inducer, this should make the version update PRs be auto merged if CI passes.

**Comment by inducer** [comment]
Sounds good, thanks!

**Comment by isuruf** [comment]
What do you think about https://github.com/conda-forge/genpy-feedstock as well? It's a dependency of loopy.

**Comment by inducer** [comment]
I don't know. I won't turn it down, but I wonder whether these Py-only packages aren't better served by just being on the package index rather than on the package index *and* on conda forge.

**Comment by isuruf** [comment]
I think it's been worked on https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/pip-interoperability.html#improving-interoperability-with-pip

**Comment by inducer** [comment]
Sure. Then, for things that are already in CF, I'm not opposed to bot automerge. Thanks for suggesting it.

**Pull request merged**
